import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'LeemaWebtech App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (  
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
